package notification

import (
	"time"

	"github.com/google/uuid"
)

// Type identifies the reason a notification was generated.
type Type string

const (
	TypePriceDrop Type = "price_drop"
	TypeTargetHit Type = "target_hit"
	TypeTrendAlert Type = "trend_alert"
)

// Notification is an in-app notification generated by the scheduler or agents.
type Notification struct {
	ID        uuid.UUID  `json:"id"`
	MissionID uuid.UUID  `json:"missionId"`
	ItemID    *uuid.UUID `json:"itemId,omitempty"`
	Type      Type       `json:"type"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	Read      bool       `json:"read"`
	CreatedAt time.Time  `json:"createdAt"`
}

// CreateRequest is the payload for creating a notification (internal use only).
type CreateRequest struct {
	MissionID uuid.UUID
	ItemID    *uuid.UUID
	Type      Type
	Title     string
	Body      string
}
