package notification

import (
	"time"

	"github.com/google/uuid"
)

// Notification is an in-app notification generated by the scheduler or agents.
type Notification struct {
	ID        uuid.UUID  `json:"id"`
	MissionID uuid.UUID  `json:"missionId"`
	ItemID    *uuid.UUID `json:"itemId,omitempty"`
	Type      string     `json:"type"`  // price_drop | target_hit | trend_alert
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	Read      bool       `json:"read"`
	CreatedAt time.Time  `json:"createdAt"`
}

// CreateRequest is the payload for creating a notification (internal use only).
type CreateRequest struct {
	MissionID uuid.UUID
	ItemID    *uuid.UUID
	Type      string
	Title     string
	Body      string
}
