package template

import "github.com/jibei/scouter/internal/mission"

// catalog is the hardcoded list of built-in mission templates.
// To add a template, append an entry here — no DB migration needed.
var catalog = []Template{
	{
		Slug:        "laptop",
		Name:        "Laptop / Notebook",
		Icon:        "💻",
		Category:    "computing",
		Description: "Compare laptops by performance, portability, and price-to-value. Great for work, school, or creative workflows.",
		Constraints: []mission.Constraint{
			{Key: "ram_min_gb", Label: "Minimum RAM (GB)", Value: 16, Type: "hard"},
			{Key: "storage_min_gb", Label: "Minimum Storage (GB)", Value: 512, Type: "hard"},
			{Key: "weight_max_kg", Label: "Maximum Weight (kg)", Value: 2.0, Type: "soft"},
			{Key: "battery_min_hrs", Label: "Minimum Battery Life (hrs)", Value: 8, Type: "soft"},
		},
		CostCategories:  []string{"Device", "Accessories", "Software", "Warranty"},
		WeightProfile:   mission.WeightProfile{Price: 3, Quality: 4, Feature: 5},
		SuggestedBudget: &BudgetRange{Min: 800, Max: 2500},
	},
	{
		Slug:        "desktop",
		Name:        "Desktop PC",
		Icon:        "🖥️",
		Category:    "computing",
		Description: "Build or buy a desktop for home, office, or gaming — compare components, pre-builts, and value-per-watt.",
		Constraints: []mission.Constraint{
			{Key: "ram_min_gb", Label: "Minimum RAM (GB)", Value: 16, Type: "hard"},
			{Key: "storage_min_gb", Label: "Minimum Storage (GB)", Value: 1000, Type: "hard"},
			{Key: "gpu_required", Label: "Dedicated GPU Required", Value: true, Type: "soft"},
		},
		CostCategories:  []string{"System", "Monitor", "Peripherals", "Software", "UPS"},
		WeightProfile:   mission.WeightProfile{Price: 4, Quality: 3, Feature: 5},
		SuggestedBudget: &BudgetRange{Min: 600, Max: 3000},
	},
	{
		Slug:        "tablet",
		Name:        "Tablet",
		Icon:        "📱",
		Category:    "computing",
		Description: "Find the right tablet for reading, media, or light work — compare display quality, ecosystem, and accessories.",
		Constraints: []mission.Constraint{
			{Key: "storage_min_gb", Label: "Minimum Storage (GB)", Value: 128, Type: "hard"},
			{Key: "screen_min_inch", Label: "Minimum Screen Size (inches)", Value: 10, Type: "soft"},
			{Key: "pencil_support", Label: "Stylus / Pen Support", Value: true, Type: "soft"},
		},
		CostCategories:  []string{"Tablet", "Keyboard Case", "Stylus", "Accessories"},
		WeightProfile:   mission.WeightProfile{Price: 4, Quality: 4, Feature: 4},
		SuggestedBudget: &BudgetRange{Min: 300, Max: 1200},
	},
	{
		Slug:        "smartphone",
		Name:        "Smartphone",
		Icon:        "📲",
		Category:    "electronics",
		Description: "Compare phones by camera quality, battery life, and ecosystem — unlock or carrier-specific.",
		Constraints: []mission.Constraint{
			{Key: "storage_min_gb", Label: "Minimum Storage (GB)", Value: 128, Type: "hard"},
			{Key: "battery_min_mah", Label: "Minimum Battery (mAh)", Value: 4000, Type: "soft"},
			{Key: "os", Label: "OS (iOS / Android)", Value: "", Type: "soft"},
		},
		CostCategories:  []string{"Device", "Case", "Screen Protector", "Carrier Plan"},
		WeightProfile:   mission.WeightProfile{Price: 3, Quality: 5, Feature: 4},
		SuggestedBudget: &BudgetRange{Min: 400, Max: 1400},
	},
	{
		Slug:        "tv",
		Name:        "TV / Display",
		Icon:        "📺",
		Category:    "electronics",
		Description: "Pick the best TV or large display for your room size, viewing habits, and budget.",
		Constraints: []mission.Constraint{
			{Key: "screen_min_inch", Label: "Minimum Screen Size (inches)", Value: 55, Type: "hard"},
			{Key: "resolution", Label: "Resolution (4K / 8K)", Value: "4K", Type: "hard"},
			{Key: "hdr_support", Label: "HDR Support", Value: true, Type: "soft"},
			{Key: "refresh_min_hz", Label: "Minimum Refresh Rate (Hz)", Value: 60, Type: "soft"},
		},
		CostCategories:  []string{"TV", "Wall Mount", "Soundbar", "Cables"},
		WeightProfile:   mission.WeightProfile{Price: 3, Quality: 5, Feature: 4},
		SuggestedBudget: &BudgetRange{Min: 400, Max: 3000},
	},
	{
		Slug:        "headphones",
		Name:        "Headphones / Earbuds",
		Icon:        "🎧",
		Category:    "electronics",
		Description: "Find the best headphones or earbuds by sound profile, ANC quality, and comfort for your use case.",
		Constraints: []mission.Constraint{
			{Key: "anc_required", Label: "Active Noise Cancellation", Value: true, Type: "soft"},
			{Key: "wireless_required", Label: "Wireless / Bluetooth", Value: true, Type: "hard"},
			{Key: "battery_min_hrs", Label: "Minimum Battery Life (hrs)", Value: 20, Type: "soft"},
		},
		CostCategories:  []string{"Headphones", "Case", "Cables"},
		WeightProfile:   mission.WeightProfile{Price: 3, Quality: 5, Feature: 4},
		SuggestedBudget: &BudgetRange{Min: 50, Max: 500},
	},
	{
		Slug:        "camera",
		Name:        "Camera",
		Icon:        "📷",
		Category:    "electronics",
		Description: "Compare mirrorless, DSLR, or compact cameras by sensor size, lens ecosystem, and video capability.",
		Constraints: []mission.Constraint{
			{Key: "type", Label: "Camera Type (mirrorless / DSLR / compact)", Value: "", Type: "soft"},
			{Key: "video_4k", Label: "4K Video Required", Value: true, Type: "soft"},
			{Key: "ibis", Label: "In-Body Stabilisation", Value: true, Type: "soft"},
		},
		CostCategories:  []string{"Body", "Lenses", "Memory Cards", "Bag", "Accessories"},
		WeightProfile:   mission.WeightProfile{Price: 2, Quality: 5, Feature: 5},
		SuggestedBudget: &BudgetRange{Min: 500, Max: 4000},
	},
	{
		Slug:        "gaming-console",
		Name:        "Gaming Console",
		Icon:        "🎮",
		Category:    "electronics",
		Description: "Compare gaming consoles by exclusive titles, online ecosystem, and performance at your target resolution.",
		Constraints: []mission.Constraint{
			{Key: "target_resolution", Label: "Target Resolution (1080p / 4K)", Value: "4K", Type: "soft"},
			{Key: "online_gaming", Label: "Online Multiplayer Required", Value: true, Type: "soft"},
		},
		CostCategories:  []string{"Console", "Extra Controllers", "Games", "Subscription", "Accessories"},
		WeightProfile:   mission.WeightProfile{Price: 4, Quality: 3, Feature: 5},
		SuggestedBudget: &BudgetRange{Min: 300, Max: 800},
	},
	{
		Slug:        "trip",
		Name:        "Vacation / Trip",
		Icon:        "✈️",
		Category:    "travel",
		Description: "Plan a leisure trip — compare destinations, accommodation, flights, and total cost of the experience.",
		Constraints: []mission.Constraint{
			{Key: "duration_max_days", Label: "Maximum Trip Duration (days)", Value: 14, Type: "soft"},
			{Key: "direct_flight", Label: "Direct Flights Preferred", Value: true, Type: "soft"},
			{Key: "accommodation_stars", Label: "Minimum Hotel Stars", Value: 3, Type: "soft"},
		},
		CostCategories:  []string{"Flights", "Accommodation", "Activities", "Food", "Transport", "Insurance"},
		WeightProfile:   mission.WeightProfile{Price: 4, Quality: 4, Feature: 4},
		SuggestedBudget: &BudgetRange{Min: 1000, Max: 10000},
	},
	{
		Slug:        "road-trip",
		Name:        "Road Trip",
		Icon:        "🚗",
		Category:    "travel",
		Description: "Plan a road trip — compare routes, rental cars vs own vehicle, accommodation, and fuel costs.",
		Constraints: []mission.Constraint{
			{Key: "max_driving_hrs_per_day", Label: "Max Driving Hours / Day", Value: 6, Type: "soft"},
			{Key: "pet_friendly", Label: "Pet-Friendly Stops Required", Value: false, Type: "soft"},
		},
		CostCategories:  []string{"Fuel", "Accommodation", "Food", "Activities", "Car Rental", "Tolls"},
		WeightProfile:   mission.WeightProfile{Price: 5, Quality: 3, Feature: 4},
		SuggestedBudget: &BudgetRange{Min: 500, Max: 5000},
	},
	{
		Slug:        "kitchen-reno",
		Name:        "Kitchen Renovation",
		Icon:        "🍳",
		Category:    "renovation",
		Description: "Compare kitchen renovation options — from cosmetic upgrades to full remodels. Track cabinets, appliances, and labour.",
		Constraints: []mission.Constraint{
			{Key: "layout_change", Label: "Layout Change Required", Value: false, Type: "soft"},
			{Key: "appliances_included", Label: "New Appliances Included", Value: true, Type: "soft"},
		},
		CostCategories:  []string{"Cabinets", "Countertops", "Appliances", "Flooring", "Labour", "Plumbing", "Electrical"},
		WeightProfile:   mission.WeightProfile{Price: 4, Quality: 4, Feature: 4},
		SuggestedBudget: &BudgetRange{Min: 5000, Max: 50000},
	},
	{
		Slug:        "car",
		Name:        "Car / Vehicle",
		Icon:        "🚙",
		Category:    "custom",
		Description: "Compare vehicles by total cost of ownership, reliability, fuel type, and feature set.",
		Constraints: []mission.Constraint{
			{Key: "fuel_type", Label: "Fuel Type (gas / hybrid / electric)", Value: "", Type: "soft"},
			{Key: "seats_min", Label: "Minimum Seats", Value: 5, Type: "hard"},
			{Key: "awd_required", Label: "AWD / 4WD Required", Value: false, Type: "soft"},
		},
		CostCategories:  []string{"Purchase Price", "Insurance", "Fuel / Charging", "Maintenance", "Registration", "Financing"},
		WeightProfile:   mission.WeightProfile{Price: 4, Quality: 4, Feature: 4},
		SuggestedBudget: &BudgetRange{Min: 15000, Max: 80000},
	},
}
