package giftfinder

// catalog is the built-in list of 35 French gift ideas.
var catalog = []catalogItem{
	// Tech
	{
		id: "tech-01", name: "Carte cadeau Fnac", category: "tech",
		priceRange: "10-100€", estimatedPrice: 50,
		description: "Idéale pour acheter livres, jeux vidéo, high-tech ou musique sur Fnac.com ou en magasin.",
		occasions:   []string{"Anniversaire", "Noël", "Saint-Valentin", "Fête des Mères", "Fête des Pères"},
		recipients:  []string{"Lui", "Elle", "Enfant", "Couple"},
		platforms:   []string{"Fnac.com", "Fnac (magasin)"},
		keywords:    []string{"tech", "livre", "jeu", "musique", "fnac"},
	},
	{
		id: "tech-02", name: "Montre connectée", category: "tech",
		priceRange: "80-250€", estimatedPrice: 149,
		description: "Suivi d'activité, notifications et paiement sans contact. Modèles disponibles chez Darty, Boulanger et Amazon.",
		occasions:   []string{"Anniversaire", "Noël", "Fête des Pères"},
		recipients:  []string{"Lui", "Elle"},
		platforms:   []string{"Darty", "Boulanger", "Amazon.fr"},
		keywords:    []string{"montre", "sport", "santé", "connecté", "tech"},
	},
	{
		id: "tech-03", name: "Kindle Paperwhite", category: "tech",
		priceRange: "120-160€", estimatedPrice: 139,
		description: "Liseuse étanche avec 6 semaines d'autonomie. Parfait pour les amoureux de la lecture.",
		occasions:   []string{"Anniversaire", "Noël", "Fête des Mères"},
		recipients:  []string{"Lui", "Elle"},
		platforms:   []string{"Amazon.fr", "Fnac.com"},
		keywords:    []string{"lecture", "livre", "kindle", "tech"},
	},
	{
		id: "tech-04", name: "AirPods Pro (2e génération)", category: "tech",
		priceRange: "250-280€", estimatedPrice: 265,
		description: "Écouteurs sans fil Apple avec réduction de bruit active. Disponibles chez la Fnac, Darty et Apple Store.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Lui", "Elle"},
		platforms:   []string{"Apple Store", "Fnac.com", "Darty"},
		keywords:    []string{"musique", "audio", "écouteurs", "apple", "tech"},
	},
	{
		id: "tech-05", name: "Enceinte Bluetooth JBL Flip 7", category: "tech",
		priceRange: "100-140€", estimatedPrice: 119,
		description: "Enceinte portable étanche avec 12h d'autonomie. Idéale pour voyager ou profiter en plein air.",
		occasions:   []string{"Anniversaire", "Noël", "Fête des Pères"},
		recipients:  []string{"Lui", "Elle", "Couple"},
		platforms:   []string{"Amazon.fr", "Boulanger", "Darty"},
		keywords:    []string{"musique", "enceinte", "bluetooth", "voyage", "tech"},
	},
	{
		id: "tech-06", name: "Tablette iPad (10e génération)", category: "tech",
		priceRange: "360-460€", estimatedPrice: 389,
		description: "Tablette Apple polyvalente pour la famille, les études ou le divertissement.",
		occasions:   []string{"Noël", "Anniversaire"},
		recipients:  []string{"Lui", "Elle", "Enfant", "Couple"},
		platforms:   []string{"Apple Store", "Fnac.com", "Darty"},
		keywords:    []string{"tablette", "apple", "tech", "ipad"},
	},
	{
		id: "tech-07", name: "DJI Mini 4 Pro (drone)", category: "tech",
		priceRange: "750-900€", estimatedPrice: 799,
		description: "Drone compact 4K avec obstacle avoidance. Parfait pour capturer des souvenirs de voyage.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Lui"},
		platforms:   []string{"DJI.com", "Fnac.com", "Amazon.fr"},
		keywords:    []string{"drone", "photo", "voyage", "tech"},
	},
	// Mode
	{
		id: "mode-01", name: "Écharpe en cachemire", category: "mode",
		priceRange: "60-150€", estimatedPrice: 89,
		description: "Écharpe douce et élégante en pur cachemire. Un cadeau intemporel pour l'hiver.",
		occasions:   []string{"Noël", "Anniversaire", "Saint-Valentin"},
		recipients:  []string{"Lui", "Elle"},
		platforms:   []string{"Monoprix", "Galeries Lafayette", "Le Bon Marché"},
		keywords:    []string{"mode", "vêtement", "hiver", "luxe"},
	},
	{
		id: "mode-02", name: "Sac à main cuir Made in France", category: "mode",
		priceRange: "80-200€", estimatedPrice: 120,
		description: "Sac artisanal en cuir véritable, fabriqué en France. Disponible chez Longchamp ou A.P.C.",
		occasions:   []string{"Anniversaire", "Saint-Valentin", "Fête des Mères", "Noël"},
		recipients:  []string{"Elle"},
		platforms:   []string{"Longchamp.com", "APC.fr", "Galeries Lafayette"},
		keywords:    []string{"sac", "cuir", "mode", "luxe", "femme"},
	},
	{
		id: "mode-03", name: "Coffret cravates & pochette", category: "mode",
		priceRange: "40-80€", estimatedPrice: 55,
		description: "Coffret élégant avec cravate en soie et pochette assortie. Idéal pour offrir du style.",
		occasions:   []string{"Anniversaire", "Fête des Pères", "Noël"},
		recipients:  []string{"Lui"},
		platforms:   []string{"Galeries Lafayette", "Le Bon Marché", "Brice"},
		keywords:    []string{"cravate", "mode", "homme", "élégance"},
	},
	{
		id: "mode-04", name: "Sneakers de créateur", category: "mode",
		priceRange: "80-180€", estimatedPrice: 120,
		description: "Baskets tendance signées Veja, Sézane ou Isabel Marant — style parisien garanti.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Lui", "Elle"},
		platforms:   []string{"Veja-store.com", "Sezane.com", "Zalando.fr"},
		keywords:    []string{"chaussures", "sneakers", "mode", "tendance"},
	},
	// Beauté
	{
		id: "beaute-01", name: "Coffret parfum de luxe", category: "beauté",
		priceRange: "60-150€", estimatedPrice: 90,
		description: "Coffret avec eau de parfum et miniatures assorties de grandes maisons : Chanel, Dior, YSL.",
		occasions:   []string{"Noël", "Saint-Valentin", "Fête des Mères", "Anniversaire"},
		recipients:  []string{"Elle"},
		platforms:   []string{"Sephora.fr", "Marionnaud", "Nocibé"},
		keywords:    []string{"parfum", "beauté", "luxe", "cosmétique"},
	},
	{
		id: "beaute-02", name: "Coffret soin visage Rituals", category: "beauté",
		priceRange: "35-75€", estimatedPrice: 55,
		description: "Coffret rituel spa comprenant crème, huile de bain et gommage. Cadeau bien-être très apprécié.",
		occasions:   []string{"Noël", "Saint-Valentin", "Fête des Mères", "Anniversaire"},
		recipients:  []string{"Elle"},
		platforms:   []string{"Rituals.com", "Sephora.fr", "Nocibé"},
		keywords:    []string{"soin", "spa", "beauté", "bien-être"},
	},
	{
		id: "beaute-03", name: "Box beauté Birchbox (3 mois)", category: "beauté",
		priceRange: "30-45€", estimatedPrice: 39,
		description: "Abonnement découverte de produits beauté sélectionnés chaque mois, livraison à domicile.",
		occasions:   []string{"Anniversaire", "Noël", "Saint-Valentin"},
		recipients:  []string{"Elle"},
		platforms:   []string{"Birchbox.fr"},
		keywords:    []string{"beauté", "cosmétique", "abonnement", "découverte"},
	},
	{
		id: "beaute-04", name: "Épilateur Braun Silk-épil", category: "beauté",
		priceRange: "60-120€", estimatedPrice: 79,
		description: "Épilateur rechargeable avec tête 40 pince-poils. Résultats durables jusqu'à 4 semaines.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Elle"},
		platforms:   []string{"Darty", "Amazon.fr", "Boulanger"},
		keywords:    []string{"beauté", "épilateur", "soin"},
	},
	// Maison
	{
		id: "maison-01", name: "Robot cuiseur Thermomix TM6", category: "maison",
		priceRange: "1299-1499€", estimatedPrice: 1399,
		description: "Robot multifonction haut de gamme pour cuisiner facilement. Référence en France pour la cuisine connectée.",
		occasions:   []string{"Noël", "Anniversaire"},
		recipients:  []string{"Couple", "Elle"},
		platforms:   []string{"Thermomix.fr"},
		keywords:    []string{"cuisine", "robot", "maison", "gastronomie"},
	},
	{
		id: "maison-02", name: "Cafetière Nespresso Vertuo Next", category: "maison",
		priceRange: "80-140€", estimatedPrice: 99,
		description: "Cafetière à capsules avec technologie centrifusion pour un café parfait chaque matin.",
		occasions:   []string{"Anniversaire", "Noël", "Fête des Pères"},
		recipients:  []string{"Lui", "Elle", "Couple"},
		platforms:   []string{"Nespresso.com", "Amazon.fr", "Darty"},
		keywords:    []string{"café", "maison", "cuisine", "nespresso"},
	},
	{
		id: "maison-03", name: "Bougie parfumée Diptyque", category: "maison",
		priceRange: "40-70€", estimatedPrice: 52,
		description: "Bougie parfumée artisanale de la maison parisienne Diptyque. Durée de combustion 60h.",
		occasions:   []string{"Noël", "Saint-Valentin", "Anniversaire", "Fête des Mères"},
		recipients:  []string{"Lui", "Elle", "Couple"},
		platforms:   []string{"Diptyque.com", "Le Bon Marché", "Sephora.fr"},
		keywords:    []string{"bougie", "maison", "luxe", "parfum"},
	},
	{
		id: "maison-04", name: "Robot aspirateur Roomba", category: "maison",
		priceRange: "200-500€", estimatedPrice: 299,
		description: "Aspirateur robot intelligent avec cartographie automatique de votre domicile.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Couple", "Lui", "Elle"},
		platforms:   []string{"Boulanger", "Darty", "Amazon.fr"},
		keywords:    []string{"aspirateur", "robot", "maison", "tech"},
	},
	{
		id: "maison-05", name: "Appareil à raclette Tefal", category: "maison",
		priceRange: "40-90€", estimatedPrice: 59,
		description: "Appareil à raclette 8 personnes avec plaques antiadhésives amovibles. Parfait pour les soirées conviviales.",
		occasions:   []string{"Noël", "Anniversaire"},
		recipients:  []string{"Couple", "Lui", "Elle"},
		platforms:   []string{"Fnac.com", "Darty", "Amazon.fr"},
		keywords:    []string{"raclette", "maison", "cuisine", "convivialité"},
	},
	{
		id: "maison-06", name: "Livre de recettes Cyril Lignac", category: "maison",
		priceRange: "20-35€", estimatedPrice: 29,
		description: "Dernier ouvrage du chef préféré des Français avec 100 recettes accessibles et gourmandes.",
		occasions:   []string{"Anniversaire", "Noël", "Fête des Mères", "Fête des Pères"},
		recipients:  []string{"Lui", "Elle"},
		platforms:   []string{"Fnac.com", "Amazon.fr", "FNAC (magasin)"},
		keywords:    []string{"cuisine", "livre", "gastronomie", "recette"},
	},
	// Expériences
	{
		id: "exp-01", name: "Coffret Wonderbox Spa & Bien-être", category: "expérience",
		priceRange: "40-120€", estimatedPrice: 69,
		description: "Accès à plus de 700 spas et instituts de beauté en France. Valable 18 mois.",
		occasions:   []string{"Anniversaire", "Saint-Valentin", "Fête des Mères", "Noël"},
		recipients:  []string{"Elle", "Couple"},
		platforms:   []string{"Wonderbox.fr", "Amazon.fr", "Fnac.com"},
		keywords:    []string{"spa", "bien-être", "expérience", "détente"},
	},
	{
		id: "exp-02", name: "Séjour hôtel boutique 2 nuits", category: "expérience",
		priceRange: "150-350€", estimatedPrice: 220,
		description: "Week-end en hôtel de charme, disponible via Smartbox ou directement sur Booking.com.",
		occasions:   []string{"Anniversaire", "Saint-Valentin", "Noël"},
		recipients:  []string{"Couple"},
		platforms:   []string{"Smartbox.fr", "Booking.com", "La Clef des Villes"},
		keywords:    []string{"voyage", "hôtel", "week-end", "expérience"},
	},
	{
		id: "exp-03", name: "Cours de cuisine gastronomique", category: "expérience",
		priceRange: "60-150€", estimatedPrice: 90,
		description: "Atelier cuisine animé par un chef professionnel dans les grandes villes françaises.",
		occasions:   []string{"Anniversaire", "Fête des Pères", "Saint-Valentin", "Noël"},
		recipients:  []string{"Lui", "Elle", "Couple"},
		platforms:   []string{"Laboitedecours.com", "Les Cours Halles", "Wonderbox.fr"},
		keywords:    []string{"cuisine", "gastronomie", "cours", "expérience"},
	},
	{
		id: "exp-04", name: "Concert ou spectacle (place)", category: "expérience",
		priceRange: "30-120€", estimatedPrice: 65,
		description: "Billet pour un concert, une comédie musicale ou une pièce de théâtre selon les goûts du destinataire.",
		occasions:   []string{"Anniversaire", "Noël", "Saint-Valentin"},
		recipients:  []string{"Lui", "Elle", "Couple"},
		platforms:   []string{"Fnac Spectacles", "Ticketmaster.fr", "Billetreduc.com"},
		keywords:    []string{"spectacle", "musique", "concert", "théâtre", "expérience"},
	},
	{
		id: "exp-05", name: "Journée au parc Astérix ou Disneyland Paris", category: "expérience",
		priceRange: "55-120€", estimatedPrice: 80,
		description: "Billet d'entrée pour une journée magique en famille ou en amoureux.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Enfant", "Couple"},
		platforms:   []string{"Disneylandparis.com", "Parcasterix.fr", "Fnac Spectacles"},
		keywords:    []string{"parc", "famille", "enfant", "expérience", "loisir"},
	},
	{
		id: "exp-06", name: "Abonnement Netflix ou Disney+ (1 an)", category: "expérience",
		priceRange: "60-100€", estimatedPrice: 79,
		description: "Carte cadeau d'abonnement streaming pour profiter de films et séries en illimité.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Lui", "Elle", "Couple", "Enfant"},
		platforms:   []string{"Fnac.com", "Amazon.fr"},
		keywords:    []string{"streaming", "série", "film", "expérience", "abonnement"},
	},
	// Gastronomie
	{
		id: "gastro-01", name: "Coffret vins de Bordeaux (6 bouteilles)", category: "gastronomie",
		priceRange: "40-120€", estimatedPrice: 75,
		description: "Sélection de 6 bouteilles de Bordeaux, accompagnée de notes de dégustation.",
		occasions:   []string{"Anniversaire", "Noël", "Fête des Pères"},
		recipients:  []string{"Lui", "Couple"},
		platforms:   []string{"Cdiscount.com", "Millesima.fr", "Le Bon Marché"},
		keywords:    []string{"vin", "bordeaux", "gastronomie", "alcool"},
	},
	{
		id: "gastro-02", name: "Coffret champagne Moët & Chandon", category: "gastronomie",
		priceRange: "40-80€", estimatedPrice: 55,
		description: "Bouteille de Moët Impérial avec deux flûtes gravées pour célébrer un moment spécial.",
		occasions:   []string{"Anniversaire", "Saint-Valentin", "Noël"},
		recipients:  []string{"Couple", "Lui", "Elle"},
		platforms:   []string{"Moët.com", "Nicolas.fr", "Amazon.fr"},
		keywords:    []string{"champagne", "célébration", "gastronomie", "alcool"},
	},
	{
		id: "gastro-03", name: "Abonnement Cheese Geek (fromages)", category: "gastronomie",
		priceRange: "35-70€", estimatedPrice: 49,
		description: "Sélection mensuelle de fromages artisanaux français livrés à domicile avec fiches de dégustation.",
		occasions:   []string{"Anniversaire", "Noël", "Fête des Pères"},
		recipients:  []string{"Lui", "Couple"},
		platforms:   []string{"La Fromagerie en ligne", "Terroir Direct"},
		keywords:    []string{"fromage", "gastronomie", "abonnement", "artisanal"},
	},
	{
		id: "gastro-04", name: "Box gastronomique Terroirs du Monde", category: "gastronomie",
		priceRange: "30-60€", estimatedPrice: 45,
		description: "Coffret de produits régionaux français : foie gras, truffes, miel, confits et épices.",
		occasions:   []string{"Noël", "Anniversaire", "Fête des Pères", "Fête des Mères"},
		recipients:  []string{"Lui", "Elle", "Couple"},
		platforms:   []string{"Terroir-direct.com", "Amazon.fr", "Fnac.com"},
		keywords:    []string{"gastronomie", "terroir", "france", "coffret"},
	},
	{
		id: "gastro-05", name: "Cours de dégustation de vins", category: "gastronomie",
		priceRange: "45-90€", estimatedPrice: 65,
		description: "Atelier oenologie d'1h30 animé par un sommelier pour apprendre à déguster le vin.",
		occasions:   []string{"Anniversaire", "Fête des Pères", "Saint-Valentin"},
		recipients:  []string{"Lui", "Couple"},
		platforms:   []string{"O'Chateau.com", "Laboitedecours.com", "Wonderbox.fr"},
		keywords:    []string{"vin", "oenologie", "gastronomie", "cours", "expérience"},
	},
	// Enfants
	{
		id: "enfant-01", name: "Lego Technic (set 18+)", category: "jeux & jouets",
		priceRange: "40-200€", estimatedPrice: 80,
		description: "Set LEGO Technic pour enfants et adolescents passionnés de mécanique et de construction.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Enfant"},
		platforms:   []string{"LEGO.com", "Amazon.fr", "Fnac.com"},
		keywords:    []string{"lego", "jouet", "construction", "enfant"},
	},
	{
		id: "enfant-02", name: "Console Nintendo Switch Lite", category: "jeux & jouets",
		priceRange: "200-250€", estimatedPrice: 219,
		description: "Console portable Nintendo pour enfants et ados avec accès à des centaines de jeux.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Enfant"},
		platforms:   []string{"Fnac.com", "Amazon.fr", "Micromania"},
		keywords:    []string{"jeu", "nintendo", "console", "enfant", "tech"},
	},
	{
		id: "enfant-03", name: "Livre jeunesse illustré", category: "jeux & jouets",
		priceRange: "10-25€", estimatedPrice: 15,
		description: "Album illustré ou roman jeunesse d'un auteur français primé. Idéal dès 3 ans.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Enfant"},
		platforms:   []string{"Fnac.com", "Amazon.fr", "Libraire locale"},
		keywords:    []string{"livre", "enfant", "lecture", "cadeau"},
	},
	// Sport
	{
		id: "sport-01", name: "Abonnement salle de sport (3 mois)", category: "sport",
		priceRange: "60-150€", estimatedPrice: 90,
		description: "Carte cadeau pour 3 mois d'accès à un club de fitness (Basic-Fit, Neoness, Club Med Gym).",
		occasions:   []string{"Anniversaire", "Noël", "Fête des Pères"},
		recipients:  []string{"Lui", "Elle"},
		platforms:   []string{"Basic-Fit.com", "Neoness.fr"},
		keywords:    []string{"sport", "fitness", "santé", "abonnement"},
	},
	{
		id: "sport-02", name: "Vélo électrique Decathlon", category: "sport",
		priceRange: "600-1200€", estimatedPrice: 799,
		description: "VAE Decathlon B'TWIN avec 60km d'autonomie. Idéal pour les trajets urbains ou le loisir.",
		occasions:   []string{"Anniversaire", "Noël"},
		recipients:  []string{"Lui", "Elle"},
		platforms:   []string{"Decathlon.fr", "Decathlon (magasin)"},
		keywords:    []string{"vélo", "sport", "électrique", "écologie"},
	},
}
